### ISSUE TITLE
A-buffer - billboard

### ISSUE THREAD

**Issue by Zsupi** [Zsupi/VolumeRendering#16]
## Description
Create metaballs with A-Buffer technic.
## Todo
 - [ ] Create Program and shader with empty VBO
 - [ ] Create SSBO with all the metaball positions
 - [ ] Create a billboard on each of the metaballs
 - [ ] Draw the billboards
