### ISSUE TITLE
A-buffer - linked list

### ISSUE THREAD

**Issue by Zsupi** [Zsupi/VolumeRendering#17]
## Description
Optimize Metaball rendering with A-buffer technic
## Todo
- [ ] Don't draw the billboards
- [ ] Create a linked list from the metaballs (SSBO)
- [ ] Create a pixel-sized array (SSBO)
- [ ] Implement the A-Buffer creation with atomicExchange and atomicIncrease
- [ ] Bind the 2 SSBOs into the metaball rendering pipeline
- [ ] Draw the metaballs
