### ISSUE TITLE
Metaballs

### ISSUE THREAD

**Issue by Zsupi** [Zsupi/VolumeRendering#2]
# Tasks:

- [ ] Render multiple metaballs
- [ ] Make 3D texture working
- [ ] Render a static Volume
